# Generated by Django 5.2 on 2026-08-15 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Display name for public profile', max_length=255)),
                ('bio', models.TextField(blank=True, help_text='Short biography')),
                ('location', models.CharField(blank=True, help_text='User location', max_length=255)),
                ('avatar_url', models.URLField(blank=True, help_text='URL to profile avatar')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('website', models.URLField(blank=True, help_text='Personal website URL')),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of skills (JSON array of strings)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
